name: Build and Tag

permissions:
  contents: write
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.23.1'

      - name: Build
        run: go build -v ./...

      - name: Get next version from conventional commits
        id: conventional_version
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          default_bump: patch

      - name: Create and push tag
        if: ${{ steps.conventional_version.outputs.new_version != steps.conventional_version.outputs.previous_version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag v${{ steps.conventional_version.outputs.new_version }}
          git push origin v${{ steps.conventional_version.outputs.new_version }}