name: Build, Test and Tag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build -v ./...

      - name: Get next version from conventional commits
        id: conventional_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          default_bump: patch

      - name: Create and push tag
        if: ${{ steps.conventional_version.outputs.new_version != steps.conventional_version.outputs.previous_version }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.conventional_version.outputs.new_version }}
          git push origin v${{ steps.conventional_version.outputs.new_version }}